name: macOS CI

on:
  push:
    branches: [ spds ]
  pull_request:
    branches: [ spds ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: cd jvm && chmod +x gradlew
    - name: Set gradle settings
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: printf "SCALA_VERSION=3.0.0\nUSERNAME=$USERNAME\nPASSWORD=$PASSWORD\n" > jvm/gradle.properties
    - name: Add swift-demangle to PATH
      run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        cp /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-demangle $GITHUB_WORKSPACE/bin/
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
    - name: Build everything
      run: ./build.sh
    - name: Analysis regression tests
      run: cd tests && ./test.bash
