name: Ubuntu CI

on:
  push:
    branches: [ spds ]
  pull_request:
    branches: [ spds ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: sersoft-gmbh/SwiftyActions@v1
      with:
        release-version: 5.4
        platform: ubuntu-20.04 # ubuntu-latest doesn't work
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: cd jvm && chmod +x gradlew
    - name: Set gradle settings
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: printf "SCALA_VERSION=2.13.5\nUSERNAME=$USERNAME\nPASSWORD=$PASSWORD\n" > jvm/gradle.properties
    - name: Build and test jvm/ with Gradle
      run: cd jvm && ./gradlew build -i
    - name: Build everything
      run: ./build.sh
    - name: Analysis regression tests
      run: cd tests && ./test.bash